/* ==========================================================================
   CODE-KATZE · levels.js  ·  JONFIE STUDIOS
   --------------------------------------------------------------------------
   ALLE Level-Daten des Spiels (aus game.js ausgelagert, damit neue Level
   leicht gepflegt werden können). Wird in index.html VOR game.js geladen.

   Jedes Level ist eine "Karte" aus Textzeilen. Ein Zeichen pro Feld:
       .  = freies Feld
       K  = Katze (Startposition)
       F  = Fisch / Ziel
       W  = Wasserpfütze (Hindernis 💧)
       H  = Hund (Hindernis 🐶)
       Z  = Zaun (Hindernis 🚧)
       S  = Sammelobjekt (🧶) – muss VOR dem Ziel eingesammelt werden
   'blick' = Startblickrichtung: 0=oben, 1=rechts, 2=unten, 3=links.
   'min'   = Länge der kürzesten Lösung (per Breitensuche berechnet; dient
             der Sortierung, zur Laufzeit wird sie frisch berechnet).
   'ziel'  = { i: Emoji, n: Name im Satz } – was die Katze am Ziel findet.

   Zusätzliche (optionale) Felder für Spezial-Level:
       budget: 4     -> Baustein-Budget: das Programm darf höchstens so
                        viele Bausteine haben (erzwingt Schleifen 🔁)
       nebel: true   -> Nebel-Level: nur die Umgebung der Katze ist sichtbar
       sammel: {...} -> eigenes Emoji/Name für Sammelobjekte
                        (Standard: { i: '🧶', n: 'das Wollknäuel' })

   Die Kern-Level jeder Stufe sind aufsteigend nach 'min' sortiert;
   Spezial-Level (Budget/Nebel/Sammeln) stehen am Ende ihrer Stufe.
   ========================================================================== */

'use strict';

const STANDARD_ZIEL = { i: '🐟', n: 'den Fisch' };

const SCHWIERIGKEITEN = {

  leicht: {
    label: "Leicht",
    farbe: "#3ec96a",
    levels: [
      { blick: 0, min: 2, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        '.....',
        '..F..',
        '.....',
        '..K..',
        '.....',
      ]},
      { blick: 1, min: 2, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        '.....',
        '.....',
        '...F.',
        '...K.',
        '.....',
      ]},
      { blick: 0, min: 3, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        '.....',
        '..K.F',
        '.....',
        '.....',
        '.....',
      ]},
      { blick: 0, min: 4, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        '.....',
        '.....',
        '.....',
        '....K',
        '...F.',
      ]},
      { blick: 3, min: 5, ziel: { i: '🐦', n: 'den Vogel' }, karte: [
        'HK...',
        '.....',
        'F....',
        '.....',
        '.....',
      ]},
      { blick: 0, min: 5, ziel: { i: '🦋', n: 'den Schmetterling' }, karte: [
        '.....',
        '.....',
        'WK...',
        'F....',
        '.....',
      ]},
      { blick: 1, min: 5, ziel: { i: '🐛', n: 'die Raupe' }, karte: [
        '...K.',
        '..FW.',
        '.....',
        '.....',
        '.....',
      ]},
      { blick: 1, min: 6, ziel: { i: '🍗', n: 'das Hähnchen' }, karte: [
        '.....',
        '.FH..',
        '.....',
        '..K..',
        '.....',
      ]},
      { blick: 0, min: 6, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        '.WF..',
        '.....',
        '.....',
        'WK...',
        '.....',
      ]},
      { blick: 0, min: 6, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        '.....',
        '.....',
        'KH...',
        '.....',
        '.FW..',
      ]},
      { blick: 0, min: 6, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        '.....',
        '..F..',
        '.....',
        '.....',
        '....K',
      ]},
      { blick: 0, min: 7, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        '.W..K',
        '.F..W',
        '.....',
        '.....',
        '.....',
      ]},
      { blick: 0, min: 7, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        '.....',
        '..W.F',
        'W....',
        '.....',
        '..K..',
      ]},
      { blick: 3, min: 7, ziel: { i: '🐦', n: 'den Vogel' }, karte: [
        '......',
        '..H..F',
        '..K...',
        'W.....',
        '.W....',
        '......',
      ]},
      { blick: 1, min: 8, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'W.....',
        '...F..',
        '...W..',
        '.....W',
        '.....W',
        '.K....',
      ]},
      { blick: 0, min: 8, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        '...H..',
        '....W.',
        '.K.W..',
        '.....F',
        '.....W',
        '......',
      ]},
      { blick: 2, min: 9, ziel: { i: '🦋', n: 'den Schmetterling' }, karte: [
        '...W.K',
        '.....H',
        '......',
        '..W...',
        '.....F',
        '......',
      ]},
      { blick: 1, min: 9, ziel: { i: '🍗', n: 'das Hähnchen' }, karte: [
        'W..FH.',
        '......',
        '......',
        '......',
        '.....W',
        '....K.',
      ]},
      { blick: 1, min: 9, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        'H..K.W',
        'W.....',
        '......',
        '....H.',
        '......',
        '.....F',
      ]},
      { blick: 0, min: 11, ziel: { i: '🐛', n: 'die Raupe' }, karte: [
        '......',
        'K...W.',
        '......',
        '..W...',
        '......',
        '..W.F.',
      ]},
      { blick: 3, min: 13, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        '..WWHF',
        '.W....',
        '......',
        '......',
        '......',
        'K.....',
      ]},
      { blick: 0, min: 5, budget: 3, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        'WFW.H.',
        'W.W...',
        'W.W.W.',
        'W.W...',
        'W.W.H.',
        'WKW...',
      ]},
    ],
  },

  mittel: {
    label: "Mittel",
    farbe: "#ff8a5c",
    levels: [
      { blick: 0, min: 7, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        '.F...',
        '....W',
        '....K',
        '.....',
        '..W.W',
      ]},
      { blick: 0, min: 7, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        '..WK.',
        'F....',
        '..H..',
        '.....',
        '.WH..',
      ]},
      { blick: 2, min: 7, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        'K....',
        '..W..',
        'H.F..',
        '...H.',
        'H....',
      ]},
      { blick: 3, min: 8, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        'W....',
        '...H.',
        'K....',
        'W...F',
        '.....',
      ]},
      { blick: 1, min: 8, ziel: { i: '🐦', n: 'den Vogel' }, karte: [
        '.W.F.',
        '.W.H.',
        '.....',
        '...H.',
        '.K.H.',
      ]},
      { blick: 3, min: 9, ziel: { i: '🍗', n: 'das Hähnchen' }, karte: [
        '...FH',
        '....W',
        'WH...',
        'K...W',
        '....H',
      ]},
      { blick: 0, min: 10, ziel: { i: '🐛', n: 'die Raupe' }, karte: [
        'WWW..',
        '..W..',
        '.H...',
        'F.H.K',
        '.....',
      ]},
      { blick: 2, min: 11, ziel: { i: '🦋', n: 'den Schmetterling' }, karte: [
        '....F',
        '..H.W',
        'W....',
        'W.W..',
        'K....',
      ]},
      { blick: 0, min: 11, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'FW....',
        '......',
        'W.....',
        '.W.W..',
        '..W...',
        'W..WK.',
      ]},
      { blick: 2, min: 11, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        'K.....',
        'W.WWH.',
        '.H....',
        '..HH..',
        '...H.F',
        '......',
      ]},
      { blick: 3, min: 12, ziel: { i: '🦋', n: 'den Schmetterling' }, karte: [
        '.....W',
        'K.H..W',
        '.WHW..',
        '..W.WF',
        '......',
        '.....W',
      ]},
      { blick: 3, min: 13, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        '.F..W.',
        '..H.W.',
        '.H....',
        '....W.',
        'W..W..',
        '..W..K',
      ]},
      { blick: 0, min: 14, ziel: { i: '🐦', n: 'den Vogel' }, karte: [
        'WW.F..',
        'KW..W.',
        '..W...',
        '..H..W',
        '.....W',
        '....W.',
      ]},
      { blick: 0, min: 14, ziel: { i: '🐛', n: 'die Raupe' }, karte: [
        '....KW',
        '...WH.',
        '.HW...',
        '.HWW..',
        '..W...',
        '..F.W.',
      ]},
      { blick: 1, min: 15, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        '......',
        '..W...',
        '..W...',
        '...W.F',
        '...HWH',
        '.K.W..',
      ]},
      { blick: 2, min: 15, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        '.H.WW.',
        '.....K',
        '.W..H.',
        '..WHHW',
        '....F.',
        '....WH',
      ]},
      { blick: 0, min: 16, ziel: { i: '🍗', n: 'das Hähnchen' }, karte: [
        '.....W',
        'W..K.W',
        'WH....',
        '.WH.W.',
        '.WFH..',
        '......',
      ]},
      { blick: 2, min: 16, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        '.K....',
        '.W....',
        'WH.WW.',
        'HWW...',
        '.W.W.W',
        '.W.F..',
      ]},
      { blick: 0, min: 16, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        '.HW..W',
        '...WHK',
        'W.WW..',
        'H..W..',
        'F.W..W',
        '......',
      ]},
      { blick: 0, min: 17, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'H..WKH',
        '.H....',
        'WH..W.',
        'W.HW..',
        'F....W',
        '......',
      ]},
      { blick: 0, min: 19, budget: 7, ziel: { i: '🦋', n: 'den Schmetterling' }, karte: [
        '...Z.F',
        '..Z..Z',
        '.Z..Z.',
        'Z..Z..',
        '..Z...',
        'KZ....',
      ]},
      { blick: 0, min: 9, budget: 7, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        'WWWWWW',
        'W....F',
        'W.WWWW',
        'W.W...',
        'W.W.H.',
        'WKW...',
      ]},
    ],
  },

  schwer: {
    label: "Schwer",
    farbe: "#e23b3b",
    levels: [
      { blick: 1, min: 11, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'H.....',
        '..K.WW',
        '..H...',
        '...H..',
        '.H....',
        '.F.W..',
      ]},
      { blick: 1, min: 13, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        '.....K',
        'WW....',
        '..W.H.',
        'W.H..H',
        'F...H.',
        '......',
      ]},
      { blick: 1, min: 15, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        '..W...',
        'FH...H',
        '...W.W',
        'W.....',
        '....W.',
        '.W.HK.',
      ]},
      { blick: 1, min: 17, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        '.H....',
        '.WFW..',
        '..HKW.',
        '....H.',
        '......',
        '....H.',
      ]},
      { blick: 0, min: 18, ziel: { i: '🦋', n: 'den Schmetterling' }, karte: [
        'K.W.HH',
        '.....W',
        '.H....',
        'H...W.',
        '..WWWW',
        '....F.',
      ]},
      { blick: 0, min: 19, ziel: { i: '🐛', n: 'die Raupe' }, karte: [
        'K...H.',
        '.W.HFH',
        '.WHW..',
        '..W...',
        'W...W.',
        'WH..H.',
      ]},
      { blick: 0, min: 21, ziel: { i: '🐦', n: 'den Vogel' }, karte: [
        '.KH...',
        '..H.F.',
        '.W..W.',
        '.H..HW',
        '.H.H.W',
        '......',
      ]},
      { blick: 0, min: 21, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        'HWH....',
        '......W',
        '.H.HW..',
        'FW.H...',
        'WW.WW..',
        '..WKW..',
        '.H.....',
      ]},
      { blick: 0, min: 21, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        '..H..H.',
        'WW..WH.',
        '.H....F',
        '...HHHW',
        '..WH..W',
        'H..W.K.',
        '.......',
      ]},
      { blick: 0, min: 23, ziel: { i: '🍗', n: 'das Hähnchen' }, karte: [
        'FHWWWK',
        '..HH..',
        '...W..',
        '...W.H',
        '...H.H',
        '.W....',
      ]},
      { blick: 3, min: 23, ziel: { i: '🦋', n: 'den Schmetterling' }, karte: [
        '...HHF.',
        'WH.H...',
        'W..HW.H',
        'K.WH...',
        '..H.HH.',
        '.H.....',
        '...W.HW',
      ]},
      { blick: 3, min: 24, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        'F....H.',
        '....HH.',
        '..HW...',
        '...WKW.',
        'WH..WH.',
        '.H.....',
        'H.WH...',
      ]},
      { blick: 3, min: 24, ziel: { i: '🍗', n: 'das Hähnchen' }, karte: [
        '...HWFH',
        '.H..H.H',
        '..KW...',
        '.H..HH.',
        '..H..H.',
        '.WW.W..',
        'WWW...H',
      ]},
      { blick: 2, min: 26, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'W.....W',
        '.W....K',
        '....WWW',
        '...H.FW',
        '..HW...',
        '...W..W',
        '.H...W.',
      ]},
      { blick: 1, min: 26, ziel: { i: '🐛', n: 'die Raupe' }, karte: [
        '..H..W.',
        'W...W.H',
        '..H...H',
        'KWWW..H',
        'WF..W.W',
        '.H.....',
        '.WW.HWW',
      ]},
      { blick: 2, min: 27, ziel: { i: '🥛', n: 'die Milch' }, karte: [
        'WW.H.FH',
        '..W..WW',
        'W...WKW',
        'W..W...',
        'W.H..W.',
        '....H..',
        'WW.HWWW',
      ]},
      { blick: 2, min: 28, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        'WHW.W.H',
        '.HFHHHW',
        'W..W...',
        'H.H..W.',
        'W.W..H.',
        'W.W.W.K',
        'W...W..',
      ]},
      { blick: 1, min: 30, ziel: { i: '🐦', n: 'den Vogel' }, karte: [
        '..W.WH.',
        'W..H...',
        '.W...W.',
        '...W.W.',
        '.WW.W..',
        '.FH...H',
        '...WKWW',
      ]},
      { blick: 3, min: 30, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'HHW....',
        '.H..W..',
        '.H.WH..',
        'H...WW.',
        'H..WW..',
        '..WK..H',
        'HFH.WHH',
      ]},
      { blick: 3, min: 30, ziel: { i: '🧶', n: 'das Wollknäuel' }, karte: [
        'F.WHK.W',
        'W..HH..',
        'HW.WWW.',
        '.W..W..',
        'WHH...W',
        'W.WH..W',
        '..WW.H.',
      ]},
      { blick: 0, min: 15, budget: 11, ziel: { i: '🍗', n: 'das Hähnchen' }, karte: [
        'WWWWWWW',
        'W.....W',
        'W.ZZZ.W',
        'W.ZZZ.W',
        'W.ZZZ.W',
        'W.ZZZFW',
        'WKWWWWW',
      ]},
      { blick: 1, min: 13, nebel: true, ziel: { i: '🐦', n: 'den Vogel' }, karte: [
        '......F',
        '.W..H..',
        '...W...',
        '.H...W.',
        '..W....',
        '....H..',
        'K......',
      ]},
      { blick: 0, min: 10, budget: 7, nebel: true, ziel: { i: '🐭', n: 'die Maus' }, karte: [
        'ZZZZZZZ',
        'Z....FZ',
        'Z.ZZZZZ',
        'Z.Z.W..',
        'Z.Z..H.',
        'Z.Z....',
        'ZKZ..W.',
      ]},
      { blick: 3, min: 14, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'F..W...',
        '...H...',
        '..W....',
        '.S...W.',
        '....H..',
        '.W.....',
        '.....K.',
      ]},
      { blick: 0, min: 23, ziel: { i: '🐟', n: 'den Fisch' }, karte: [
        'S.....F',
        '..W.H..',
        '.......',
        '...K...',
        '.W...W.',
        '.......',
        'S....H.',
      ]},
    ],
  },
};
